### ISSUE TITLE
Time for a FHIR STU3 1.8 Release

### ISSUE THREAD

**Issue by cjduffett** [intervention-engine/fhir#109]
The latest FHIR candidate is now 1.8, see http://hl7.org/fhir/2017Jan/index.html. Among other things this renames "MedicationOrder" to "MedicationRequest" and changes some attributes of this model. Since Synthea was upgraded to FHIR STU3 1.8 the latest Synthea output is no longer compatible with 1.6.

**Comment by cmoesel** [comment]
Ugh.  First they changed `MedicationPrescription` to `MedicationOrder`.  Now they're changing `MedicationOrder` to `MedicationRequest`...

To do this work there are a few things we want to be sure of first.  The main thing is that the current FHIR generator is in sync with the current fhir (1.6) codebase.  In other words, when you run the generator and copy the files into the fhir repo, there should be no diffs (except that one timestamp in the conformance file).  Once this is confirmed, we can create a new branch of the fhir generator and rebase it on top of the HL7 FHIR 1.8 branch.  Then we re-generate the code, and... voila!  You have FHIR 1.8 code with a bunch of outdated or obsolete tests to fix!

**Comment by cjduffett** [comment]
I made sure the stu3_2016 branches of the FHIR server and generator are now in sync. I'm going to try the rebase now... wish me luck!

**Comment by cjduffett** [comment]
Rebasing from this commit: https://github.com/hl7-fhir/fhir-svn/commit/797efb4a16c4fc47f0c8a2cd9a4ac4bc7871527b
