### ISSUE TITLE
Tests fail on git clone (mongo_indexes_test.go)

### ISSUE THREAD

**Issue by PeterLamar** [intervention-engine/fhir#133]
Perhaps I am doing it wrong, but I am getting a fail in the mongo index test. I have mongo installed and running, missing another prereq?

ok  	fhir/auth	0.024s
ok  	fhir/models	0.025s
ok  	fhir/search	1.904s
--- FAIL: TestMongoIndexes (0.00s)
panic: mkdir ./testdb: file exists [recovered]
	panic: mkdir ./testdb: file exists

goroutine 6 [running]:
testing.tRunner.func1(0xc4202120f0)
	/usr/local/go/src/testing/testing.go:711 +0x2d2
panic(0xf049e0, 0xc4201df080)
	/usr/local/go/src/runtime/panic.go:491 +0x283
fhir/server.(*MongoIndexesTestSuite).SetupSuite(0xc42016ab40)
	/home/plamar/go/src/fhir/server/mongo_indexes_test.go:54 +0x84f
github.com/stretchr/testify/suite.Run(0xc4202120f0, 0x178c4a0, 0xc42016ab40)
	/home/plamar/go/src/github.com/stretchr/testify/suite/suite.go:64 +0x63b
fhir/server.TestMongoIndexes(0xc4202120f0)
	/home/plamar/go/src/fhir/server/mongo_indexes_test.go:96 +0x51
testing.tRunner(0xc4202120f0, 0x10b3a88)
	/usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de
FAIL	fhir/server	0.035s
ok  	fhir/upload	0.025s

**Comment by eug48** [comment]
You might need to delete the "testdb" directory that is created by that test suite.

**Comment by PeterLamar** [comment]
Got it working after a few restarts and adjusting of Mongo. Thanks!
