### ISSUE TITLE
Installation Issues on Mac OS X

### ISSUE THREAD

**Issue by aviars** [intervention-engine/fhir#28]
First I clone to `github.com/intervention-engine\fhir`. MongoDB 3+ is already running. The tests fail and the server startup fails although it does appear to connect to MongoDB.  

Here is the test output:

    $ go test ./...
    # github.com/intervention-engine/fhir/models
    models/bundle_test.go:8:2: cannot find package "github.com/bitly/go-simplejson" in any of:
	/usr/local/go/src/github.com/bitly/go-simplejson (from $GOROOT)
	/Users/alan/Documents/work/src/github.com/bitly/go-simplejson (from $GOPATH)
    FAIL	github.com/intervention-engine/fhir/models [setup failed]
    # github.com/intervention-engine/fhir/search
    search/mongo_search_test.go:15:2: cannot find package "github.com/pebbe/util" in any of:
	/usr/local/go/src/github.com/pebbe/util (from $GOROOT)
	/Users/alan/Documents/work/src/github.com/pebbe/util (from $GOPATH)
    FAIL	github.com/intervention-engine/fhir/search [setup failed]
    # github.com/intervention-engine/fhir/server
    search/mongo_search_test.go:15:2: cannot find package "github.com/pebbe/util" in any of:
	/usr/local/go/src/github.com/pebbe/util (from $GOROOT)
	/Users/alan/Documents/work/src/github.com/pebbe/util (from $GOPATH)
    FAIL	github.com/intervention-engine/fhir/server [setup failed]
    # github.com/intervention-engine/fhir/upload
    search/mongo_search_test.go:15:2: cannot find package "github.com/pebbe/util" in any of:
	/usr/local/go/src/github.com/pebbe/util (from $GOROOT)
	/Users/alan/Documents/work/src/github.com/pebbe/util (from $GOPATH)
    FAIL	github.com/intervention-engine/fhir/upload [setup failed]
    ?   	github.com/intervention-engine/fhir	[no test files]

Here is the output from the server start attempt:

    $go run server.go
    panic: no reachable servers

    goroutine 1 [running]:
    github.com/intervention-engine/fhir/server.(*FHIRServer).Run(0xc820101ee8)
	/Users/alan/Documents/work/src/github.com/intervention-engine/fhir/server/server_setup.go:34 +0xa8
    main.main()
	/Users/alan/Documents/work/src/github.com/intervention-engine/fhir/server.go:13 +0x15f

    goroutine 17 [syscall, locked to thread]:
    runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

    goroutine 20 [sleep]:
    time.Sleep(0x1dcd6500)
	/usr/local/go/src/runtime/time.go:59 +0xf9
    gopkg.in/mgo%2ev2.(*mongoCluster).syncServersLoop(0xc8200bc200)
	/Users/alan/Documents/work/src/gopkg.in/mgo.v2/cluster.go:386 +0x484
    created by gopkg.in/mgo%2ev2.newCluster
	/Users/alan/Documents/work/src/gopkg.in/mgo.v2/cluster.go:78 +0x1d0

    goroutine 55 [sleep]:
    time.Sleep(0x37e11d600)
	/usr/local/go/src/runtime/time.go:59 +0xf9
    gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc82019e540, 0x1)
	/Users/alan/Documents/work/src/gopkg.in/mgo.v2/server.go:296 +0x1b0
    created by gopkg.in/mgo%2ev2.newServer
	/Users/alan/Documents/work/src/gopkg.in/mgo.v2/server.go:89 +0x160

    goroutine 26 [sleep]:
    time.Sleep(0x37e11d600)
	/usr/local/go/src/runtime/time.go:59 +0xf9
    gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc8201480e0, 0x1)
	/Users/alan/Documents/work/src/gopkg.in/mgo.v2/server.go:296 +0x1b0
    created by gopkg.in/mgo%2ev2.newServer
	/Users/alan/Documents/work/src/gopkg.in/mgo.v2/server.go:89 +0x160

    goroutine 31 [sleep]:
    time.Sleep(0x37e11d600)
	/usr/local/go/src/runtime/time.go:59 +0xf9
    gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc8201481c0, 0x1)
	/Users/alan/Documents/work/src/gopkg.in/mgo.v2/server.go:296 +0x1b0
    created by gopkg.in/mgo%2ev2.newServer
	/Users/alan/Documents/work/src/gopkg.in/mgo.v2/server.go:89 +0x160

    goroutine 32 [sleep]:
    time.Sleep(0x37e11d600)
	/usr/local/go/src/runtime/time.go:59 +0xf9
    gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc8201482a0, 0x1)
	/Users/alan/Documents/work/src/gopkg.in/mgo.v2/server.go:296 +0x1b0
    created by gopkg.in/mgo%2ev2.newServer
	/Users/alan/Documents/work/src/gopkg.in/mgo.v2/server.go:89 +0x160

    goroutine 45 [sleep]:
    time.Sleep(0x37e11d600)
	/usr/local/go/src/runtime/time.go:59 +0xf9
    gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc82015ac40, 0x1)
	/Users/alan/Documents/work/src/gopkg.in/mgo.v2/server.go:296 +0x1b0
    created by gopkg.in/mgo%2ev2.newServer
	/Users/alan/Documents/work/src/gopkg.in/mgo.v2/server.go:89 +0x160

    goroutine 80 [sleep]:
    time.Sleep(0x37e11d600)
	/usr/local/go/src/runtime/time.go:59 +0xf9
    gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc820148a80, 0x1)
	/Users/alan/Documents/work/src/gopkg.in/mgo.v2/server.go:296 +0x1b0
    created by gopkg.in/mgo%2ev2.newServer
	/Users/alan/Documents/work/src/gopkg.in/mgo.v2/server.go:89 +0x160

    goroutine 61 [sleep]:
    time.Sleep(0x37e11d600)
	/usr/local/go/src/runtime/time.go:59 +0xf9
    gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc82019eb60, 0x1)
	/Users/alan/Documents/work/src/gopkg.in/mgo.v2/server.go:296 +0x1b0
    created by gopkg.in/mgo%2ev2.newServer
	/Users/alan/Documents/work/src/gopkg.in/mgo.v2/server.go:89 +0x160

    goroutine 70 [sleep]:
    time.Sleep(0x37e11d600)
	/usr/local/go/src/runtime/time.go:59 +0xf9
    gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc820148700, 0x1)
	/Users/alan/Documents/work/src/gopkg.in/mgo.v2/server.go:296 +0x1b0
    created by gopkg.in/mgo%2ev2.newServer
	/Users/alan/Documents/work/src/gopkg.in/mgo.v2/server.go:89 +0x160

    goroutine 75 [sleep]:
    time.Sleep(0x37e11d600)
	/usr/local/go/src/runtime/time.go:59 +0xf9
    gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc8201488c0, 0x1)
	/Users/alan/Documents/work/src/gopkg.in/mgo.v2/server.go:296 +0x1b0
    created by gopkg.in/mgo%2ev2.newServer
	/Users/alan/Documents/work/src/gopkg.in/mgo.v2/server.go:89 +0x160

    goroutine 82 [sleep]:
    time.Sleep(0x37e11d600)
	/usr/local/go/src/runtime/time.go:59 +0xf9
    gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc82015ad20, 0x1)
	/Users/alan/Documents/work/src/gopkg.in/mgo.v2/server.go:296 +0x1b0
    created by gopkg.in/mgo%2ev2.newServer
	/Users/alan/Documents/work/src/gopkg.in/mgo.v2/server.go:89 +0x160

    goroutine 102 [sleep]:
    time.Sleep(0x37e11d600)
	/usr/local/go/src/runtime/time.go:59 +0xf9
    gopkg.in/mgo%2ev2.(*mongoServer).pinger(0xc82020a1c0, 0x1)
	/Users/alan/Documents/work/src/gopkg.in/mgo.v2/server.go:296 +0x1b0
    created by gopkg.in/mgo%2ev2.newServer
	/Users/alan/Documents/work/src/gopkg.in/mgo.v2/server.go:89 +0x160
    exit status 2

**Comment by aviars** [comment]
Any of your teaming going to there FHIR connect-a-thon in Orlando this weekend?

**Comment by cmoesel** [comment]
We develop and run on Macs, with MongoDB 3.2.0, so it _should_ be possible to get it running...  That said, I'm not entirely sure what's going on...

*Regarding Tests:*  It looks like the tests aren't finding their dependencies in your GOPATH.  Did you run `go get -t`?  If so, and you still get this error, you might try `go get -t ./...`.

*Regarding Server Startup:* You said "it does appear to connect to MongoDB" -- but I'm not seeing anything in your logs that would indicate such.  Usually the `panic: no reachable servers` means it didn't connect to MongoDB.

It's expecting to connect via _localhost_ and the default MongoDB port _27017_.  Do you have any networking things (firewall, etc) that might interfere with that?  Have you tried to connect using a MongoDB client to verify that MongoDB is working correctly?

*Regarding the Connectathon:* There won't be anyone from the Intervention Engine team there, but some of our other colleagues will be there representing their project: _Crucible_.

Thanks for reaching out.  Let us know if any of the above helped to resolve your issues (or not).

**Comment by aviars** [comment]
thank you @cmoesel After installing 1.4.2 go in my user directory and running `go get -t ./...` the packages. were actually downloaded.  `go get` by itself appeared to do nothing.  Tests also appear to run okay.  Now sorting out `ie`, `frontend`, and `tools`.  I understand that `ie` and `fhir` need to be running to get the `frontend` going but both `ie` and `fhir` bind to port 3001. I'll close this issue and open another.
