### ISSUE TITLE
Running IE and FHIR in parrallel

### ISSUE THREAD

**Issue by aviars** [intervention-engine/fhir#29]
Both of servers, `fhit` and `ie`, bind to port 3001.  I understand both need to be running but maybe I'm missing something.  Is there an up and running guide that outlines setup for all the inter-related components?

**Comment by cmoesel** [comment]
The `ie` server actually includes the `fhir` server in it -- so you _don't_ need to run both at the same time.  Run `fhir` if you _only_ need a RESTful FHIR server.  Run `ie` if you plan to actually run the full Intervention Engine software (with frontend).  The running `ie` server will respond to standard fhir requests and a few custom ie requests needed by the frontend.

I apologize that there isn't a better guide for getting all of this running.  I'll try to get something posted soon, but here is the general gist of it (assuming you've done the go 1.5 installation and `go get`s on each golang project).

1. Run the ie server from the _ie_ repo: `go run server.go` (if it's the first time, pass the `-loadCodes` flag to load ICD 9 codes into the database for code-complete in the UI)
2. Run the risk services from the _riskservice_ repo: `go run riskservice.go` (if it's the first time, pass the argument `-registerURL http://localhost:3001` to register it for notifications from the ie server)
3. If you want some synthetic patient records in the system, run the patient generator from the _tools_ repo: `go run generate.go -fhirURL http://localhost:3001 -n 20` (change `20` to however many records you want, but note that some parts of the frontend don't do paging yet, so high numbers aren't recommended)
4. Create yourself a user and password using the ie-user tool in the _tools_ repo: `go run ie-user.go add bob foobar` (where `bob` is the username and `foobar` is the password)
5. Run the frontend from the _frontend_ repo by following instructions [here](https://github.com/intervention-engine/frontend/blob/master/README.md)
6. Go to http://localhost:4200 in your browser and login using the credentials you created in step 4.

**Comment by aviars** [comment]
Thanks @cmoesel .  I'll work from these notes for now.

**Comment by aviars** [comment]
@cmoesel you mention 1.5.  Does that mean I should use go 1.5 instead of 1.4? README in fhir says 1.4.

**Comment by cmoesel** [comment]
Ah, shoot.  To be honest, I'm not sure.  We've been using FHIR 1.5 since it was released -- and I don't recall if we're using any 1.5 features.  I guess the fhir readme hasn't been updated to reflect that.

If you're already running 1.4, I'd go ahead and try -- but if you get any compile errors, it probably means you need to bump to 1.5.  I apologize.  This is still very much an ALPHA (or pre-ALPHA) project, so in the flurry of development, sometimes the docs fall behind...  Thanks for the extra motivation to get them in line.

**Comment by aviars** [comment]
No problem. So far so good on go 1.4.  I'm working with Debbie B and Mark M at ONC and just taking a close look at options for FHIR servers for a couple different projects.  As documentation emerges, I'm glad to try and follow it and provide feedback.  I'm a developer familiar with MongoDB but new to Golang so I'd be a good candidate as someone to validate install instructions.

**Comment by cmoesel** [comment]
BTW-- if you're interested only in the FHIR server, there's no need to mess with _ie_, _riskservice_, _frontend_, etc...  but I suspect you already know that.
