### ISSUE TITLE
Using PUT to store a Bundle results in an error

### ISSUE THREAD

**Issue by mlos100** [intervention-engine/fhir#34]
An attempt to PUT a Bundle to the endpoint, /Bundle/<my uiid id here> with an assigned Id in the uri and in the document results in an error 500.  

The console only reports  ERROR | echo | Invalid Id

**Comment by cmoesel** [comment]
What is the format of the ID you are posting?  If I had a guess, based on the error message, I'm thinking that our code currently only works with Mongo's BSON hex style ID.  Ideally, we should probably be more lenient about our IDs -- but that may be a bit of work.

If you need to get this working _now_, I'd suggest you send BSON hex IDs, if possible.

**Comment by mlos100** [comment]
It was not a Mongo BSON hex style ID.   (e.g., 30bb101f-a121-4624-a920-67be9cb82c74)

Tried using a BSON Hex ID.  Still error 500.  Log message is ERROR | echo | not found
POSTing w/o an id works fine and should suffice.

**Comment by cmoesel** [comment]
OK.  Looks like we need to test and fix PUT with an ID though.  I don't expect non-Mongo IDs to work, but I *do* expect Mongo IDs to work -- so there must be a bug.  We should fix that, and then we can think about supporting other style IDs.  Thanks again.
