### ISSUE TITLE
JSON representation of Parameters is missing resourceType property

### ISSUE THREAD

**Issue by mlos100** [intervention-engine/fhir#35]
The Parameters map is missing, "resourceType": "Parameters".

Add a MarshalJSON() method in Parameters.go (I don't know if this would go on ParametersParametersComponent (which is where UnmarshalJSON is located) or directly on Parameters

**Comment by cmoesel** [comment]
I think this is because our generator only generates the custom MarshalJSON for domain resources, and Parameters is a base resource.  This should be fairly easy to fix in the generator.  Thanks for reporting it.
