### ISSUE TITLE
Content-Type of responses for FHIR Resources should be application/json+fhir

### ISSUE THREAD

**Issue by mlos100** [intervention-engine/fhir#36]
FHIR Spec (DSTU2) Section 2.1.0.6 () states the formal mime type for fhir resources is application/json+fhir.
The formal MIME-type for FHIR resources is application/xml+fhir or application/json+fhir. The correct mime type SHALL be used by clients and servers: 
• XML: application/xml+fhir
• JSON: application/json+fhir

The intervention engine FHIR server returns application/json

**Comment by cmoesel** [comment]
Unfortunately, this will probably mean we can't use some of the nice built-in goodies in Echo.  We'll have to look at it to see what the implications are.  Thanks for submitting.
